### ISSUE TITLE
verify feditest profile

### ISSUE THREAD

**Issue by andypiper** [fediverse-devnet/fedidevs.org#12]
@feditest@mastodon.social also lists fedidevs.org in the Mastodon profile links; add a link rel attribute to validate the connection here.

**Comment by jernst** [comment]
The link is there, but not being picked up. Does the `rel=me` need double quotes?

**Comment by andypiper** [comment]
On the main fedidevs.org page, the link is 

`<a rel=me href=https://mastodon.social/@fedidevs>`

(so, no, it should not need double quotes)

There is currently no link for the @feditest profile, but I can add one in.

**Comment by andypiper** [comment]
Fixed in https://github.com/fediverse-devnet/fedidevs.org/commit/60539988a6091e95e5925596d264c524aa05981e (it may take a moment for the mastodon.social profile page to flip to green link; it is working on a federated copy of the profile)
