### ISSUE TITLE
cant open menu on mobile :(

### ISSUE THREAD

**Issue by sneakers-the-rat** [fediverse-devnet/fedidevs.org#15]
I am trying to open the menu and cannot!

Screen recording showing taps:

https://github.com/fediverse-devnet/fedidevs.org/assets/12961499/58513a7d-a017-4bd3-b31e-65ad69eff3c5

Browser: Firefox
OS: GrapheneOS

Sry not more details! Am currently still on phone!

**Comment by jernst** [comment]
And this one to pull the new version of the theme in ... https://github.com/fediverse-devnet/fedidevs.org/pull/32
